# The 'image' parameter is undocumented but required.
# The 'season' parameter is undocumented.

### Overview
GET https://api.listenbrainz.org/1/art/year-in-music/2023/{{lb-user-name}}
  ?image=overview

### Stats
GET https://api.listenbrainz.org/1/art/year-in-music/2023/{{lb-user-name}}
  ?image=stats

### Artists
GET https://api.listenbrainz.org/1/art/year-in-music/2023/{{lb-user-name}}
  ?image=artists

### Tracks
GET https://api.listenbrainz.org/1/art/year-in-music/2023/{{lb-user-name}}
  ?image=tracks

### Albums
GET https://api.listenbrainz.org/1/art/year-in-music/2023/{{lb-user-name}}
  ?image=albums

### Playlist: Discovery
GET https://api.listenbrainz.org/1/art/year-in-music/2023/{{lb-user-name}}
  ?image=discovery-playlist

### Playlist: Missed Tracks
GET https://api.listenbrainz.org/1/art/year-in-music/2023/{{lb-user-name}}
  ?image=missed-playlist
