### Find Sexy Playlists
GET https://api.listenbrainz.org/1/playlist/search
  ?query=Sexy

### Find Sexy Playlists (subset)
GET https://api.listenbrainz.org/1/playlist/search
  ?query=Sexy
  &count=69
