### Beatles vs Stones
POST https://api.listenbrainz.org/1/popularity/artist
Content-Type: application/json

{
  "artist_mbids": [
    "b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d",
    "b071f9fa-14b0-4217-8e97-eb41da73f598"
  ]
}
