### Me (This Week)
GET https://api.listenbrainz.org/1/stats/user/{{lb-user-name}}/genre-activity
  ?range=this_week

### Me (This Month)
GET https://api.listenbrainz.org/1/stats/user/{{lb-user-name}}/genre-activity
  ?range=this_month

### Me (This Year)
GET https://api.listenbrainz.org/1/stats/user/{{lb-user-name}}/genre-activity
  ?range=this_year

### Me (All Time)
GET https://api.listenbrainz.org/1/stats/user/{{lb-user-name}}/genre-activity
  ?range=all_time
