# LB-1837:
# - The documentation says the query parameter is 'name', but it's actually 'query'.
# - Also, it seems to search ALL playlists, not just the users like the documentation suggests.

### Me
GET https://api.listenbrainz.org/1/user/{{lb-user-name}}/playlists/search
  ?query="Science Fiction"

### Rob (subset)
GET https://api.listenbrainz.org/1/user/wilwheaton/playlists/search
  ?query=Shut Up Wesley
  &count=3
