### My Similar Users Feed
GET https://api.listenbrainz.org/1/user/{{lb-user-name}}/feed/events/listens/similar
Authorization: Token {{lb-user-token}}

### My Similar Users Feed (Last Item)
GET https://api.listenbrainz.org/1/user/{{lb-user-name}}/feed/events/listens/similar
  ?count=1
Authorization: Token {{lb-user-token}}

### My Similar Users Feed (2024)
GET https://api.listenbrainz.org/1/user/{{lb-user-name}}/feed/events/listens/similar
  ?min_ts=1704067200
  &max_ts=1735689599
Authorization: Token {{lb-user-token}}
